name: amplify_datastore
description: The Amplify Flutter DataStore category plugin.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_datastore

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"
  amplify_api_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_api_plugin_interface"
  plugin_platform_interface:
  amplify_datastore_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_datastore_plugin_interface"
  date_time_format:
  meta:
  collection:

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_datastore
        pluginClass: AmplifyDataStorePlugin
      ios:
        pluginClass: AmplifyDataStorePlugin
