name: amplify_flutter
description: The top level module for Amplify Flutter.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_flutter

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
  amplify_api_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_api_plugin_interface"
  amplify_storage_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_storage_plugin_interface"
  amplify_analytics_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_analytics_plugin_interface"
  amplify_auth_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_auth_plugin_interface"
  amplify_datastore_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_datastore_plugin_interface"
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify
        pluginClass: Amplify
      ios:
        pluginClass: Amplify
