name: amplify_storage_s3
description: The Amplify Flutter Storage category plugin using the AWS S3 provider.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_storage_s3

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify_core.git
      ref: "v0.1.6"
      path: "packages/amplify_flutter/"

  amplify_api_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify_api_plugin_interface.git
      ref: "v0.1.6"
      path: "packages/amplify_flutter/"

  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_storage_s3
        pluginClass: AmplifyStorageS3Plugin
      ios:
        pluginClass: AmplifyStorageS3Plugin
