name: amplify_storage_plugin_interface
description: The platform interface for the storage module of Amplify Flutter.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_storage_plugin_interface

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta:
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"
