name: amplify_auth_cognito
description: The Amplify Flutter Auth category plugin using the AWS Cognito provider.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_auth_cognito

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"
  amplify_api_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_api_plugin_interface"
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_auth_cognito
        pluginClass: AuthCognito
      ios:
        pluginClass: AuthCognito
