name: amplify_analytics_pinpoint
description: The Amplify Flutter Analytics category plugin using the AWS Pinpoint provider.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_pinpoint

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"
  amplify_analytics_plugin_interface:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_analytics_plugin_interface"
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_analytics_pinpoint
        pluginClass: AmplifyAnalyticsPinpointPlugin
      ios:
        pluginClass: AmplifyAnalyticsPinpointPlugin
