name: amplify_datastore_plugin_interface
description: The platform interface for the DataStore module of Amplify Flutter.
version: 0.1.6
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_datastore_plugin_interface

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: "<=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  meta:
  collection:
  date_time_format:
  uuid:
  amplify_core:
    git:
      url: https://github.com/luiz-simples/amplify-flutter.git
      ref: "v0.1.6"
      path: "packages/amplify_core"
